import type { Stylist, Hairstyle, Booking, User } from '@/types';

export const MOCK_HAIRSTYLES: Hairstyle[] = [
  {
    id: '1',
    name: 'Box Braids',
    description: 'Classic protective style with square-shaped sections. Versatile and long-lasting.',
    imageUrl: 'https://images.unsplash.com/photo-1605980776566-0486c3ac7617?w=600&q=80',
    category: 'Braids',
    tags: ['protective', 'long-lasting', 'versatile'],
    popularityScore: 95,
  },
  {
    id: '2',
    name: 'Knotless Braids',
    description: 'Feed-in braids that start naturally without a knot for reduced tension.',
    imageUrl: 'https://images.unsplash.com/photo-1601379760883-1bb497c558d1?w=600&q=80',
    category: 'Braids',
    tags: ['natural', 'protective', 'trendy'],
    popularityScore: 98,
  },
  {
    id: '3',
    name: 'Locs / Dreadlocks',
    description: 'Natural locking of hair strands into rope-like sections. Timeless and cultural.',
    imageUrl: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&q=80',
    category: 'Natural',
    tags: ['natural', 'cultural', 'low-maintenance'],
    popularityScore: 88,
  },
  {
    id: '4',
    name: 'Cornrows',
    description: 'Rows of tight braids worked very close to the scalp. Great base for many styles.',
    imageUrl: 'https://images.unsplash.com/photo-1513379733131-47fc74b45fc7?w=600&q=80',
    category: 'Braids',
    tags: ['scalp', 'neat', 'geometric'],
    popularityScore: 91,
  },
  {
    id: '5',
    name: 'Afro',
    description: 'Natural round shape celebrating the full texture of natural hair.',
    imageUrl: 'https://images.unsplash.com/photo-1531891437562-4301cf35b7e4?w=600&q=80',
    category: 'Natural',
    tags: ['natural', 'bold', 'volume'],
    popularityScore: 87,
  },
  {
    id: '6',
    name: 'Fade & Taper',
    description: 'Precision cut with graduating length from short to shorter. Sharp and clean.',
    imageUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=600&q=80',
    category: 'Barbering',
    tags: ['precision', 'clean', 'masculine'],
    popularityScore: 96,
  },
  {
    id: '7',
    name: 'Senegalese Twist',
    description: 'Rope-like twists using synthetic hair for an elegant, elongated look.',
    imageUrl: 'https://images.unsplash.com/photo-1499557354967-2b2d8910bcca?w=600&q=80',
    category: 'Braids',
    tags: ['elegant', 'protective', 'length'],
    popularityScore: 89,
  },
  {
    id: '8',
    name: 'TWA (Teeny Weeny Afro)',
    description: 'Short natural cut celebrating close-cropped natural texture.',
    imageUrl: 'https://images.unsplash.com/photo-1526413232644-8a40f03cc03b?w=600&q=80',
    category: 'Natural',
    tags: ['short', 'bold', 'low-maintenance'],
    popularityScore: 82,
  },
  {
    id: '9',
    name: 'Crochet Braids',
    description: 'Hair extensions attached to cornrows using a crochet needle for versatile looks.',
    imageUrl: 'https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?w=600&q=80',
    category: 'Extensions',
    tags: ['versatile', 'protective', 'quick'],
    popularityScore: 86,
  },
  {
    id: '10',
    name: 'Goddess Locs',
    description: 'Distressed faux locs with loose wavy ends for a boho-chic aesthetic.',
    imageUrl: 'https://images.unsplash.com/photo-1570158268183-d296b2892211?w=600&q=80',
    category: 'Locs',
    tags: ['boho', 'feminine', 'protective'],
    popularityScore: 93,
  },
  {
    id: '11',
    name: 'Low Skin Fade',
    description: 'Ultra-clean fade starting from the skin at the bottom. Premium barbering.',
    imageUrl: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=600&q=80',
    category: 'Barbering',
    tags: ['precision', 'premium', 'masculine'],
    popularityScore: 97,
  },
  {
    id: '12',
    name: 'Ghana Braids',
    description: 'Feed-in braids that start small at the hairline and increase in size.',
    imageUrl: 'https://images.unsplash.com/photo-1590577976322-3d2d6e2130d5?w=600&q=80',
    category: 'Braids',
    tags: ['cultural', 'scalp', 'statement'],
    popularityScore: 90,
  },
];

export const MOCK_STYLISTS: Stylist[] = [
  {
    id: '1',
    userId: 'u1',
    user: {
      id: 'u1',
      email: 'amaka@example.com',
      fullName: 'Amaka Okonkwo',
      avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=200&q=80',
      role: 'STYLIST',
      createdAt: '2023-01-15',
    },
    bio: 'Award-winning hair artist with 8 years of experience. Specializing in protective styles and natural hair care. Your hair is my canvas.',
    specialties: ['Braids', 'Natural Hair', 'Locs'],
    location: 'Victoria Island, Lagos',
    area: 'Victoria Island',
    rating: 4.9,
    reviewCount: 247,
    isVerified: true,
    offersHomeService: true,
    homeServiceFee: 3000,
    yearsExperience: 8,
    portfolioImages: [
      { id: 'p1', url: 'https://images.unsplash.com/photo-1605980776566-0486c3ac7617?w=400&q=80', hairstyleName: 'Box Braids' },
      { id: 'p2', url: 'https://images.unsplash.com/photo-1601379760883-1bb497c558d1?w=400&q=80', hairstyleName: 'Knotless Braids' },
      { id: 'p3', url: 'https://images.unsplash.com/photo-1513379733131-47fc74b45fc7?w=400&q=80', hairstyleName: 'Cornrows' },
      { id: 'p4', url: 'https://images.unsplash.com/photo-1570158268183-d296b2892211?w=400&q=80', hairstyleName: 'Goddess Locs' },
    ],
    services: [
      { id: 's1', stylistId: '1', name: 'Box Braids (Medium)', price: 15000, duration: 180, category: 'Braids' },
      { id: 's2', stylistId: '1', name: 'Knotless Braids', price: 22000, duration: 240, category: 'Braids' },
      { id: 's3', stylistId: '1', name: 'Cornrows (Simple)', price: 8000, duration: 90, category: 'Braids' },
      { id: 's4', stylistId: '1', name: 'Natural Hair Treatment', price: 12000, duration: 120, category: 'Natural' },
    ],
    availability: [
      { dayOfWeek: 1, startTime: '09:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 2, startTime: '09:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '09:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '09:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '09:00', endTime: '16:00', isAvailable: true },
      { dayOfWeek: 6, startTime: '10:00', endTime: '14:00', isAvailable: true },
    ],
  },
  {
    id: '2',
    userId: 'u2',
    user: {
      id: 'u2',
      email: 'tunde@example.com',
      fullName: 'Tunde Adeyemi',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
      role: 'STYLIST',
      createdAt: '2022-08-20',
    },
    bio: 'Master barber trained in London. Bringing world-class precision cuts to Lagos. Every fade tells a story.',
    specialties: ['Barbering', 'Fade', 'Beard Grooming'],
    location: 'Lekki Phase 1, Lagos',
    area: 'Lekki',
    rating: 4.8,
    reviewCount: 312,
    isVerified: true,
    offersHomeService: false,
    yearsExperience: 10,
    portfolioImages: [
      { id: 'p5', url: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400&q=80', hairstyleName: 'Fade & Taper' },
      { id: 'p6', url: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=400&q=80', hairstyleName: 'Low Skin Fade' },
    ],
    services: [
      { id: 's5', stylistId: '2', name: 'Haircut & Fade', price: 5000, duration: 45, category: 'Barbering' },
      { id: 's6', stylistId: '2', name: 'Skin Fade', price: 7000, duration: 60, category: 'Barbering' },
      { id: 's7', stylistId: '2', name: 'Beard Trim & Shape', price: 3000, duration: 30, category: 'Grooming' },
      { id: 's8', stylistId: '2', name: 'Full Groom Package', price: 12000, duration: 90, category: 'Barbering' },
    ],
    availability: [
      { dayOfWeek: 2, startTime: '08:00', endTime: '19:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '08:00', endTime: '19:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '08:00', endTime: '19:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '08:00', endTime: '19:00', isAvailable: true },
      { dayOfWeek: 6, startTime: '08:00', endTime: '19:00', isAvailable: true },
      { dayOfWeek: 0, startTime: '10:00', endTime: '16:00', isAvailable: true },
    ],
  },
  {
    id: '3',
    userId: 'u3',
    user: {
      id: 'u3',
      email: 'chisom@example.com',
      fullName: 'Chisom Eze',
      avatar: 'https://images.unsplash.com/photo-1589156229687-496a31ad1d1f?w=200&q=80',
      role: 'STYLIST',
      createdAt: '2023-03-10',
    },
    bio: 'Natural hair enthusiast and loctician. Creating beautiful loc journeys for 5+ years. Specializing in starter locs, retwists, and loc maintenance.',
    specialties: ['Locs', 'Natural Hair', 'Twists'],
    location: 'Ikeja, Lagos',
    area: 'Ikeja',
    rating: 4.7,
    reviewCount: 156,
    isVerified: true,
    offersHomeService: true,
    homeServiceFee: 2500,
    yearsExperience: 5,
    portfolioImages: [
      { id: 'p7', url: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=400&q=80', hairstyleName: 'Dreadlocks' },
      { id: 'p8', url: 'https://images.unsplash.com/photo-1570158268183-d296b2892211?w=400&q=80', hairstyleName: 'Goddess Locs' },
      { id: 'p9', url: 'https://images.unsplash.com/photo-1499557354967-2b2d8910bcca?w=400&q=80', hairstyleName: 'Senegalese Twist' },
    ],
    services: [
      { id: 's9', stylistId: '3', name: 'Starter Locs', price: 25000, duration: 300, category: 'Locs' },
      { id: 's10', stylistId: '3', name: 'Loc Retwist', price: 10000, duration: 120, category: 'Locs' },
      { id: 's11', stylistId: '3', name: 'Senegalese Twist', price: 20000, duration: 240, category: 'Braids' },
      { id: 's12', stylistId: '3', name: 'Natural Hair Consult', price: 5000, duration: 60, category: 'Natural' },
    ],
    availability: [
      { dayOfWeek: 1, startTime: '10:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '10:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '10:00', endTime: '17:00', isAvailable: true },
      { dayOfWeek: 6, startTime: '09:00', endTime: '15:00', isAvailable: true },
    ],
  },
  {
    id: '4',
    userId: 'u4',
    user: {
      id: 'u4',
      email: 'fatima@example.com',
      fullName: 'Fatima Bello',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80',
      role: 'STYLIST',
      createdAt: '2022-11-05',
    },
    bio: 'Celebrity stylist serving Lagos elite. Weaves, wigs, and silk press are my signature. Quality is non-negotiable.',
    specialties: ['Weaves', 'Wigs', 'Silk Press'],
    location: 'Banana Island, Lagos',
    area: 'Ikoyi',
    rating: 4.9,
    reviewCount: 189,
    isVerified: true,
    offersHomeService: true,
    homeServiceFee: 5000,
    yearsExperience: 12,
    portfolioImages: [
      { id: 'p10', url: 'https://images.unsplash.com/photo-1531891437562-4301cf35b7e4?w=400&q=80', hairstyleName: 'Natural Afro' },
      { id: 'p11', url: 'https://images.unsplash.com/photo-1526413232644-8a40f03cc03b?w=400&q=80', hairstyleName: 'Short Natural' },
    ],
    services: [
      { id: 's13', stylistId: '4', name: 'Weave Installation', price: 35000, duration: 180, category: 'Extensions' },
      { id: 's14', stylistId: '4', name: 'Wig Customization', price: 45000, duration: 240, category: 'Wigs' },
      { id: 's15', stylistId: '4', name: 'Silk Press', price: 18000, duration: 120, category: 'Styling' },
      { id: 's16', stylistId: '4', name: 'Deep Conditioning', price: 12000, duration: 90, category: 'Treatment' },
    ],
    availability: [
      { dayOfWeek: 2, startTime: '09:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 3, startTime: '09:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 4, startTime: '09:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 5, startTime: '09:00', endTime: '18:00', isAvailable: true },
      { dayOfWeek: 6, startTime: '10:00', endTime: '17:00', isAvailable: true },
    ],
  },
];

export const LAGOS_AREAS = [
  'Victoria Island', 'Lekki', 'Ikeja', 'Ikoyi', 'Surulere',
  'Yaba', 'Ajah', 'Maryland', 'Gbagada', 'Magodo',
  'Ojota', 'Agege', 'Ikorodu', 'Badagry', 'Epe',
];

export const HAIR_CATEGORIES = [
  'All', 'Braids', 'Natural', 'Barbering', 'Extensions', 'Locs', 'Styling',
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    customerId: 'c1',
    customer: { id: 'c1', email: 'me@email.com', fullName: 'Kemi Adeleke', role: 'CUSTOMER', createdAt: '2024-01-01' },
    stylistId: '1',
    stylist: MOCK_STYLISTS[0],
    serviceId: 's2',
    service: MOCK_STYLISTS[0].services[1],
    status: 'COMPLETED',
    locationType: 'SALON',
    scheduledAt: '2024-12-15T10:00:00Z',
    totalAmount: 22000,
    payment: { id: 'pay1', bookingId: 'b1', amount: 22000, status: 'COMPLETED', reference: 'EKO-2024-001', paidAt: '2024-12-15T09:30:00Z' },
    review: { id: 'r1', bookingId: 'b1', customerId: 'c1', customer: { id: 'c1', email: 'me@email.com', fullName: 'Kemi Adeleke', role: 'CUSTOMER', createdAt: '2024-01-01' }, stylistId: '1', rating: 5, comment: 'Amaka is incredible! My knotless braids look amazing. Will definitely book again!', createdAt: '2024-12-16T08:00:00Z' },
    createdAt: '2024-12-10T14:00:00Z',
  },
  {
    id: 'b2',
    customerId: 'c1',
    customer: { id: 'c1', email: 'me@email.com', fullName: 'Kemi Adeleke', role: 'CUSTOMER', createdAt: '2024-01-01' },
    stylistId: '2',
    stylist: MOCK_STYLISTS[1],
    serviceId: 's5',
    service: MOCK_STYLISTS[1].services[0],
    status: 'ACCEPTED',
    locationType: 'SALON',
    scheduledAt: '2025-01-20T14:00:00Z',
    totalAmount: 5000,
    payment: { id: 'pay2', bookingId: 'b2', amount: 5000, status: 'COMPLETED', reference: 'EKO-2025-001', paidAt: '2025-01-18T10:00:00Z' },
    createdAt: '2025-01-18T10:00:00Z',
  },
];
